[module]
  [module.hugoVersion]
    extended = false
    min = "0.75.0"


[[module.mounts]]
  source = "layouts"
  target = "layouts"

[[module.mounts]]
  source = "assets"
  target = "assets"

[build]
# Used by PurgeCSS
writeStats = true